### ISSUE TITLE
"restart_beginning" option is missing from /dist/videojs-offset.js

### ISSUE THREAD

**Issue by hanying33** [cladera/videojs-offset#14]
The readme file points user to the below file for source:
https://github.com/cladera/videojs-offset/blob/master/dist/videojs-offset.js

But this file doesn't include the feature for "restart_beginning" option, the "restart_beginning" option is actually implemented in:
https://github.com/cladera/videojs-offset/blob/master/src/main.js

**Comment by cladera** [comment]
Fixed!

Thanks!
