### ISSUE TITLE
Messes up videojs offset bar

### ISSUE THREAD

**Issue by ErraticFox** [cladera/videojs-offset#20]
Hello, every time I use this, it messes up the progress bar for seeking. For an example, if I click somewhere on the progress bar, it actually wont go to that point, but it'll do a point somewhere before that.

**Comment by cladera** [comment]
Can you provide a plunker reproducing the problem?

**Comment by ErraticFox** [comment]
Unfortunately, it hasn't been happening ever since last night. Though, I do know if the video is fairly short (>8 seconds~) it doesn't properly seek and just keeps restarting. I'm going to take a guess and say that's just how it handles html5 handles the video as I've seen other websites do this with short videos such as Facebook.

**Comment by cladera** [comment]
For videos that short you should check your encoding profile. I have faced problems like this myself in the past and the solution was tuning the encoding parameters such as keyframe interval. 

I'm closing this issue, if you learn more about it, feel free to reopen it.

**Comment by nikbo** [comment]
I can confirm that it's an issue with the latest versions of video.js and videojs-offset.
See example here:
https://jsfiddle.net/nikbo/wkn354au/
