### ISSUE TITLE
'ended' event does not get fired when the video has ended

### ISSUE THREAD

**Issue by guavajellyaaron** [cladera/videojs-offset#22]
Once the video has ended, the ended event does not get fired.

Here is the code I am using:
`player.offset({
        start: 10,
        end: 20,
        restart_beginning: false
    });

player.on('ended', function () {
        mediaComplete();
    });
`

I'd expect the 'mediaComplete' function to fire however, it does not get called.

Versions:
Videojs - 5.11.9
VideoJs Offset - 2.0.0-beta.0

**Comment by cladera** [comment]
@guavajellyaaron Yeah, you are right. I'll take a look.

**Comment by guavajellyaaron** [comment]
@cladera Any update on this?

**Comment by cladera** [comment]
Fixed through #23
