### ISSUE TITLE
Error When Seek and Replay

### ISSUE THREAD

**Issue by tilttran** [cladera/videojs-offset#37]
Dear Admin,

Please give a help.
When I play video, don't seek, it stop at the end time ok.
When I seek video, it doesn't stop at the end time?
When I replay video, it doesn't stop at the end time?

Thank you.
.

**Comment by cladera** [comment]
I cannot help you if you don't provide the right information. Please, use the issue template.

**Comment by cladera** [comment]
Hi @tilttran, Iast patch should fix this issue.
