### ISSUE TITLE
Start offset not working

### ISSUE THREAD

**Issue by Blacx** [cladera/videojs-offset#4]
Hi @cladera 

I think this demo (http://cladera.github.io/videojs-offset/) is do not jump to the fifth second accordance with the example code : 
```javascript
var player = videojs('video_example', {
		plugins: {
			offset: {
				start: 5,
				end: 40
			}
		}
	});
```

Can you help me, since I experienced the same problem. Thanks

**Comment by cladera** [comment]
Hi @Blacx ,

It does jump to fifth second but videojs-offset shows relative time. The actual duration of the demo's video (http://video-js.zencoder.com/oceans-clip.mp) is 46 seconds, but I'm showing just 35 seconds of that video starting at 00:00:05 and finishing at 00:00:40. Take a look at the duration of the "cut" video, you should see 35 seconds. 

Please, let me know if the plugin doesn't behave like I've explained.

**Comment by Blacx** [comment]
Hi @cladera 

Thank you for your fast response. Finally I understand.
Demo showing the duration of 35 seconds after the offset applied in the initial 5 seconds and 6 seconds to cut back because of the overall duration of the video is 46 seconds.

**Comment by cladera** [comment]
Anytime! ;)
