### ISSUE TITLE
The scrubber position is wrong when user clicks on progressbar

### ISSUE THREAD

**Issue by nikbo** [cladera/videojs-offset#43]
## Description
The scrubber is not positioned correctly when user changes it's position on progressbar
See an example here:
https://jsfiddle.net/nikbo/wkn354au/3/

#### videojs
The latest versions of video.js and videojs-offset

#### browsers
Tried on Chrome, Firefox and Safari

#### OSes
MacOS Mojave

**Comment by cladera** [comment]
@nikbo Thank you for reporting this issue. 

I'll take a look as soon as possible.

**Comment by mparisi76** [comment]
HI. Has there been a fix for this? I'm running into the same issue. Would love to use this, but I don't know if I can with that scrubber/seeking issue.

Thank you!

**Comment by chdh** [comment]
I had the same problem with Video.js v7.9.3, but with v7.8.4 it works correctly.
