### ISSUE TITLE
shows first few frames before moving to start time

### ISSUE THREAD

**Issue by elevenpast** [cladera/videojs-offset#6]
Hello,
I have noticed that if I set the offset to a very large number for the start time,  the video will start playing at 0 and before eventually jumping forward. 

Video-js version 4.12.11

offset: {
  start: 3151,
  end: 3181,
  restart_beginning: 'true'
}

Is there any way to avoid this?   Thanks a bunch, and great plugin!

Josh

**Comment by cladera** [comment]
Hello @elevenpast 

I've come across this issue as well. In my case it used to happen with mp4 videos, after an intense research I found out my videos were not "faststart" [check this out](http://www.adobe.com/devnet/video/articles/mp4_movie_atom.html). It fixed my starting delay problems.

However, I agree with you, the plugin shouldn't behave like it does for a large start number. I'll try to figure out a solution and get back to you.

Thank you.

P.D. Sorry for the delay, busy September... :(
