### ISSUE TITLE
Player "bg-video" is already initialised

### ISSUE THREAD

**Issue by nppsbh** [cladera/videojs-offset#7]
Hi
I am getting this error:
VIDEOJS: WARN: Player "bg-video" is already initialised. Options will not be applied.
Please advise.
Thanks

**Comment by cladera** [comment]
Hi @nppsbh,

That message appears when you try to initialise a videojs video twice.

For instance:

```
var bgVideo = videojs('bg-video', {
   controls: false
}); // This sentence will initialise a new videojs instance

// Later, trying to access the same video
var v = videojs('bg-video'); //This will return the same instance so bgVideo === v
var v = videojs('bg-video', {}); //This will try to initialise a new videojs instance over the same video component resulting the error you describe.
```

Hope this helps you. If not, I'm afraid you will have to ask in videojs repo beacuse this error belongs videojs.
