### ISSUE TITLE
Please make it compatible with video js version 5

### ISSUE THREAD

**Issue by paladox** [cladera/videojs-offset#8]

**Comment by cladera** [comment]
on it ;)

**Comment by paladox** [comment]
Thanks.

**Comment by rahbr** [comment]
Its compatible with v5, but doesnt work properly. When you set offset start to 15, when you try to move before 15s, It goes to zero.

**Comment by joankaradimov** [comment]
I've found an incompatibility with Video JS 5.

Some of the overridden functions that can act as both a getter and a setter are not compatible with the interface of Video JS 5. For example - `currentTime` returns the time when used as a getter, but returns `this` when used as a setter. This can be seen [here](https://github.com/videojs/video.js/blob/v5.19.2/src/js/player.js#L1658).

What is interesting is that Video JS 6 changes this behavior. It removes the documentation for the return value of the setter and returns undefined [(here)](https://github.com/videojs/video.js/blob/v6.0.0/src/js/player.js#L1710)

So depending on which version of Video JS this plugin targets it could either be a problem, or be just fine.

**Comment by cladera** [comment]
Thank you @joankaradimov 

I'm actually refactoring the whole plugin not only to make it compatible with videojs v5 but upgrading the entire source code to es6.

**Comment by joankaradimov** [comment]
Thanks @cladera for the plugin
