### ISSUE TITLE
closed caption is impaired 

### ISSUE THREAD

**Issue by jothikannan** [cladera/videojs-offset#9]
When i try this plugin with closed caption, closed caption text's are impaired with voice FF, Safari, IE
But in Chrome it working well
Am not sure what is the issue or error

please kindly help me on this

**Comment by cladera** [comment]
Hi @jothikannan , 
Never heard about this issue before. This plugin just seeks the video to the start point you configure and adjust the seek slider in order to fake a shorter duration. I fail to understand how this can affect the captioning sync. 
Are you sure you only come across this issue when using the plugin? Have you tried with the player disabled, or the start time to zero?

**Comment by jothikannan** [comment]
Yes the issue is when am using this plugin

What you mean player disabled ? 

if i start with zero , it works.

**Comment by cladera** [comment]
Sorry my bad, I wanted to say if you have tried not including the plugin? I guess you did, though.

Yes, please an example would help.

**Comment by jothikannan** [comment]
Hi @cladera 

pls find attached fiddle, you can see that the Closed caption is not synced with voice when we use offset http://jsfiddle.net/86e895ao/11/

**Comment by cladera** [comment]
@jothikannan Connot run the example due to text track fails to load the CC file. What should I do to make it work?

**Comment by jothikannan** [comment]
@cladera could you try it in your local machine ?

**Comment by jothikannan** [comment]
@cladera i sent an email with the source file, pls check it in your local machine

**Comment by jothikannan** [comment]
@cladera finally i figured out the issue myself

i updated the video.js into latest one, that fixed the issue

However i found another issue

when we use this Offset plugin the progressbar width is increasing automatically when the video is playing, refer the attached image 
![offset](https://cloud.githubusercontent.com/assets/4100047/11180160/9423e7dc-8c7e-11e5-97b4-96b7eb540f9e.png)

**Comment by cladera** [comment]
@jothikannan ok! I'll close this issue. Post the new one please.
